//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CricketPlayers.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Player
    {
        public int id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Nationality { get; set; }
        public string Current_Team { get; set; }
        public int Matches_Played { get; set; }
        public string Highest_Score { get; set; }
        public int Likes { get; set; }
        public int Dislikes { get; set; }
        public string Picture { get; set; }
        public string User { get; set; }
    }
}
